name: 🚀 Feature request
description: Suggest an idea for cit965
title: "[Feature]: "
labels: [enhancement]
assignees:
  - member1  # 这里您可以替换为您项目的成员名称
body:
  - type: input
    id: web-version
    attributes:
      label: cit965 Web端版本
      description: 请输入您当前使用的Web端版本。
      placeholder: v1.0.0
    validations:
      required: true
  - type: input
    id: server-version
    attributes:
      label: cit965 Server端版本
      description: 请输入您当前使用的Server端版本。
      placeholder: v1.0.0
    validations:
      required: true
  - type: textarea
    id: desc
    attributes:
      label: 功能描述以及必要性描述
      description: 请描述您觉得此新功能如何为cit965带来便利。
      placeholder: |
        1. 首先...
        2. 然后...
    validations:
      required: true
  - type: textarea
    id: advise
    attributes:
      label: 建议和方案
      description: 如果您有任何关于此功能的建议或方案，请在此分享。
